# Generated by Django 2.1 on 2018-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_livelobbyuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='livelobbyuser',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
