# Generated by Django 2.1 on 2018-10-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_livelobbyuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livelobbyuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
