# Generated by Django 2.1 on 2018-08-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180817_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='hosted_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(db_index=True, null=True),
        ),
    ]
