# Generated by Django 2.1 on 2018-08-18 02:31

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180817_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(null=True, validators=[events.models.future_event_time]),
        ),
    ]
