# Generated by Django 2.1 on 2018-08-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180817_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(
                db_index=True,
                null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='type',
            field=models.CharField(
                choices=[
                    ('ATTENDEE',
                     'Attendee'),
                    ('HOST',
                     'Host')],
                default='ATTENDEE',
                max_length=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(
                db_index=True,
                null=True),
        ),
    ]
