# Generated by Django 2.1 on 2018-08-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180830_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(
                choices=[('GAME', 'game')], default='GAME', max_length=25),
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
    ]
