# Generated by Django 2.1 on 2018-08-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180830_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(
                choices=[('GAME', 'Game')], default='GAME', max_length=25),
        ),
    ]
