# Generated by Django 2.1 on 2018-09-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180830_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_name',
            field=models.CharField(default='Participant', max_length=75),
        ),
        migrations.AlterField(
            model_name='event',
            name='initial_size',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
