# Generated by Django 2.1.2 on 2018-10-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180928_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='engangement_type',
            field=models.CharField(choices=[('COMPETITIVE', 'Competitive'), ('CASUAL', 'Casual')], default='CASUAL', max_length=25),
        ),
    ]
