# Generated by Django 2.1.2 on 2018-10-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_engangement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
